name: 'Bimbo Build'
description: 'build your Bimbo website'

branding:
  icon: 'shopping-cart'
  color: 'purple'

inputs:
  bimbo-path:
    description: 'the path to your Bimbo project'
    required: false
  dev-mode:
    description: 'skip git clone, use local code'
    required: false
    type: boolean
    default: false

runs:
  using: 'composite'
  steps:
    - name: Clone Bimbo
      run: |
        if [ ${{ inputs.dev-mode }} ]; then
          echo "we have Bimbo at home, skipping git clone"
        else
          LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/$1/releases/latest" | jq -r .tag_name)
          git clone --depth 1 https://github.com/iznaut/bimbo.git --branch "${LATEST_RELEASE}"
        fi
      shell: bash

    - name: Setup bun
      uses: oven-sh/setup-bun@v2

    - name: Build website
      run: |
        if [ ! ${{ inputs.dev-mode }} ]; then
          bun install --cwd ./bimbo
        else
          bun install --cwd ./
        fi
        if [ -n "${{ inputs.bimbo-path }}" ]; then
          bun main.js --path ${{ inputs.bimbo-path }} --build-only
        else
          bun main.js --path ./ --build-only
        fi
      shell: bash