name: 'Bimbo Build'
description: 'build your Bimbo website'

branding:
  icon: 'shopping-cart'
  color: 'purple'

inputs:
  bimbo-path:
    description: 'the path to your Bimbo project'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Clone Bimbo
      run: |
        git clone --depth 1 https://github.com/iznaut/bimbo.git
      shell: bash

    - name: Setup bun
      uses: oven-sh/setup-bun@v2

    - name: Build website
      run: |
        cd bimbo
        bun install
        cd ..
        if [ -n "${{ inputs.bimbo-path }}" ]; then
          bun main.js --path "${{ inputs.bimbo-path }}" --build-only
        else
          bun main.js --path ./ --build-only
        fi
      shell: bash