name: 'Bimbo Build'
description: 'build your Bimbo website'

branding:
  icon: 'shopping-cart'
  color: 'purple'

inputs:
  dev-mode:
    description: 'skip git clone, use local code'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Clone Bimbo
      run: |
        if [ ${{ inputs.dev-mode }} == 'true' ]; then
          echo "we have Bimbo at home, skipping git clone"
        else
          LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/iznaut/bimbo/releases/latest" | jq -r .tag_name)
          echo "cloning release ${LATEST_RELEASE}"
          git clone --depth 1 https://github.com/iznaut/bimbo.git --branch "${LATEST_RELEASE}"
        fi
      shell: bash

    - name: Setup bun
      uses: oven-sh/setup-bun@v2

    - name: Build website
      run: |
        if [ ${{ inputs.dev-mode }} == 'false' ]; then
          echo "using cloned Bimbo"
          bun install --cwd="./bimbo"
          bun ./bimbo/main.js --path ../ --build-only
        else
          echo "using local Bimbo"
          bun install
          bun main.js --path ./example-project --build-only
        fi
      shell: bash