name: 'Bimbo Build'
description: 'build your Bimbo website'

branding:
  icon: 'shopping-cart'
  color: 'purple'

permissions:
  contents: write

inputs:
  bimbo-path:
    description: 'the path to your Bimbo project'
    required: false
    default: './'
  dev-mode:
    description: 'use [local] code or [bleeding-edge] (clone from main branch)'
    required: false
    default: 'false' # false | local | bleeding-edge

runs:
  using: 'composite'
  steps:
    - name: Clone Bimbo
      run: |
        if [ ${{ inputs.dev-mode }} == 'local' ]; then
          echo "we have Bimbo at home, skipping git clone"
        elif [ ${{ inputs.dev-mode }} == 'bleeding-edge' ]; then
          echo "cloning main branch"
          git clone --depth 1 https://github.com/iznaut/bimbo.git
        else
          LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/iznaut/bimbo/releases/latest" | jq -r .tag_name)
          echo "cloning release ${LATEST_RELEASE}"
          git clone --depth 1 https://github.com/iznaut/bimbo.git --branch "${LATEST_RELEASE}"
        fi
      shell: bash

    - name: Setup bun
      uses: oven-sh/setup-bun@v2

    - name: Build website
      run: |
        if [ ${{ inputs.dev-mode }} == 'false' ]; then
          echo "using cloned Bimbo"
          bun install --cwd="./bimbo"
          bun ./bimbo/main.js --path ../ --deploy
        else
          echo "using local Bimbo"
          bun install
          bun main.js --path ./example-project --deploy
        fi
      shell: bash

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update content metadata post-build