globals:
    title: my cool webcomic
    description: a picture is worth a thousand words (plus a few extra if it also has words on it)
    url: cool.webcomic
    author:
        name: cool person
        url: https://coolperson.com/
        email: contact@coolperson.com

defaults:
    title: cool untitled page
    template: default.hbs
    subfolders:
        posts: # values will be used for all ContentFiles in the "content/posts" folder
            title: cool untitled post # "content/posts/my-first-post.md" has a `title` value defined, so this will not be used
            template: post.hbs # the value of `{{{_content}}}` in this template will be replaced with the body of "content/posts/my-first-post.md"
            draft: true # draft content is ignored on build and won't be published

collections:
    - name: navPages # collections can be accessed in templates using this name with a $ prefix (e.g. $navPages)
      filter:
          - key: navIndex # this filter returns only pages that have a `navIndex` key
      sort:
          - key: navIndex # this orders the pages by descending `navIndex` value
            order: ascending
    - name: allPosts
      filter:
          - key: _subfolder # keys with an _ prefix are auto-generated
            value: posts # this filter returns only pages that are inside the `content/posts`
      sort:
          - key: date
            order: descending
      rss: true # this will generate a `feed.xml` file listing the posts included in the "allPosts" group
    - name: tagged
      group:
          - key: tags
