name: Test Standalone Binaries
on:
  workflow_run:
    workflows: [Create Standalone Binaries]
    types:
      - completed

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
      - name: Download binaries
        uses: actions/download-artifact@master
        with:
          name: bin
          path: ./bin

      - name: Start Bimbo
        run: ./bin/bimbo-win

      - name: Check server status
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'http://localhost:6969/'
          responseCode: '200,500'
          timeout: 2000
          interval: 500

  test-mac:
    runs-on: macos-latest

    steps:
      - name: Download binaries
        uses: actions/download-artifact@master
        with:
          name: bin
          path: ./bin

      - name: Start Bimbo
        run: ./bin/bimbo-mac

      - name: Check server status
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'http://localhost:6969/'
          responseCode: '200,500'
          timeout: 2000
          interval: 500

  test-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Download binaries
        uses: actions/download-artifact@master
        with:
          name: bin
          path: ./bin

      - name: Start Bimbo
        run: ./bin/bimbo-linux

      - name: Check server status
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'http://localhost:6969/'
          responseCode: '200,500'
          timeout: 2000
          interval: 500

      # - name: deploy2nekoweb
      #   uses: deploy2nekoweb/deploy2nekoweb@v4
      #   with:
      #     nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
      #     # nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
      #     nekoweb-folder: 'bimbo-test'
      #     directory: './example-project/public'