name: build plus

permissions:
  contents: write
  
on:
  push:
    branches:
      - main
    paths:
      - 'version'

env:
  ITCH_USERNAME: iznaut
  ITCH_GAME_ID: bimbo

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os.runner }}
    strategy:
      matrix:
        os: [
          { runner: 'macos-latest', channel: 'macos' },
          { runner: 'macos-15-intel', channel: 'macos-intel' },
          { runner: 'ubuntu-latest', channel: 'linux' },
          { runner: 'windows-latest', channel: 'windows' }
        ]

    steps:
      - uses: actions/checkout@v6.0.3
      
      - name: Install Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 22
      - name: npm install
        uses: bahmutov/npm-install@v1
      - name: electron packager
        run: npx @electron/packager . --extra-resource project-starters/ --ignore project-starters/ --out build/ --overwrite
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ matrix.os.channel }}-plus
          path: build
  deploy:
    name: Upload to Itch
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - macos
          - macos-intel
          - linux
          - windows
    steps:
      - uses: actions/checkout@v6.0.3

      - uses: actions/download-artifact@v8
        with:
          name: ${{ matrix.channel }}-plus
          path: build/${{ matrix.channel }}-plus
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./build/${{ matrix.channel }}-plus
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}-plus
          buildNumberFile: ./version
